### ISSUE TITLE
TP GIT

### ISSUE THREAD

**Issue by vakter23** [vakter23/TP-GIT#1]
**TO-DO**
1) Creation du dépôt 
2) Recupération du dépôt
3) Proposer son fichier personnalisé 
4) Fusionner les propositions 
5) Améliorer le fichier
6) Choisir la meilleur solution

**Comment by vakter23** [comment]
J'ai crée le dépôt @PhDMlachahe @RafikDerradji, vous pouvez le récuperez

**Comment by RafikDerradji** [comment]
J'ai récuperé le dossier en clonant et j'ai crée ma branche (branch-rafik)

**Comment by RafikDerradji** [comment]
j'ai modifié le fichier README.md sur la branche rafik

**Comment by PhDMlachahe** [comment]
J'ai récuperé le dossier en clonant et j'ai crée ma branche (branch-Mlachahe).

**Comment by PhDMlachahe** [comment]
J'ai modifié le fichier README.md sur la branche Mlachahe.

**Comment by vakter23** [comment]
J'ai fusionné la branch de rafik (branch-rafik) sur la branch main

**Comment by vakter23** [comment]
Je vais créer ma branche pour modifier le fichier.

**Comment by vakter23** [comment]
j'ai créer ma branche et j'ai modifié le fichier README.md

**Comment by vakter23** [comment]
J'ai fais mon pull request par rapport à ma branche (branch-volkan)

**Comment by RafikDerradji** [comment]
J'ai fait mon pull request par rapport à ma branche ( branch-rafik).

**Comment by PhDMlachahe** [comment]
J'ai fait mon pull request par rapport à ma branche (branch-mlachahe).

**Comment by vakter23** [comment]
On a choisit mon pull request
